---
- name: Deploy Dozzle Service
  ansible.builtin.include_role:
    name: utils
    tasks_from: docker_service
  vars:
    utils_docker_service_name: "{{ dozzle_service_name }}"
    utils_docker_service_dir: "{{ dozzle_compose_dir }}"
    utils_docker_service_compose_template: "{{ playbook_dir }}/roles/{{ dozzle_service_name }}/templates/docker-compose.yml.j2"
    utils_docker_service_templates: []
