---
- name: Restart CrowdSec
  community.docker.docker_compose_v2:
    project_src: "{{ crowdsec.path }}"
    state: restarted
  become: true
  become_user: "{{ deploy_user }}"

- name: Restart Bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
