traefik_service_name: "traefik"
traefik_image: "traefik:v3.6.2"

traefik_data_dir: "{{ docker_data_dir }}/{{ traefik_service_name }}"
traefik_compose_dir: "{{ docker_config_dir }}/{{ traefik_service_name }}"

traefik_dashboard_domain: "traefik.{{ base_domain }}"

traefik_http_port: "80"
traefik_https_port: "443"

traefik_docker_network: "{{ docker_network_name }}"

# ACME / Let's Encrypt
traefik_acme_email: "{{ admin_email }}"
traefik_acme_storage: "/acme.json"
traefik_acme_staging: "false"

# Dashboard auth
traefik_dashboard_auth: "{{ vault_traefik_dashboard_auth }}"
