---
- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Restart zramswap
  ansible.builtin.systemd:
    name: zramswap
    state: restarted

- name: Enable and start network-offloads
  ansible.builtin.systemd:
    name: network-offloads
    enabled: true
    state: started
    daemon_reload: true
