matrix_service_name: "matrix"
# Используем Tuwunel вместо Conduit
matrix_image: "ghcr.io/matrix-construct/tuwunel:latest"

matrix_data_dir: "{{ docker_data_dir }}/{{ matrix_service_name }}"
matrix_compose_dir: "{{ docker_config_dir }}/{{ matrix_service_name }}"

matrix_server_domain: "matrix.{{ base_domain }}"
matrix_server_name: "{{ base_domain }}"

matrix_well_known_server: "matrix.{{ base_domain }}:443"
matrix_well_known_client: "https://matrix.{{ base_domain }}"

matrix_port: "6167"
matrix_registration_enabled: "true"
matrix_allow_federation: "true"
matrix_max_request_size: "20000000"
matrix_trusted_servers: '["matrix.org"]'
matrix_database_backend: "rocksdb"

# TURN настройки (список)
matrix_turn_uris:
  - "turn:turn.{{ base_domain }}:3478?transport=udp"
  - "turn:turn.{{ base_domain }}:3478?transport=tcp"

matrix_turn_secret: "{{ vault_eturnal_secret }}"
