amneziawg_service_name: "amneziawg"
amneziawg_image: "alexishw/amneziawg-web-ui:{{ amneziawg_version }}"

amneziawg_data_dir: "{{ base_docker_data_dir }}/{{ amneziawg_service_name }}"
amneziawg_compose_dir: "{{ base_docker_config_dir }}/{{ amneziawg_service_name }}"

amneziawg_domain: "{{ vpn_subdomain }}.{{ base_domain }}"
amneziawg_nginx_port: "80"
amneziawg_nginx_user: "{{ admin_username }}"
amneziawg_nginx_password: "{{ admin_password }}"

amneziawg_entrypoints: "websecure"

amneziawg_auto_start_servers: "true"
amneziawg_default_mtu: "1280"
amneziawg_default_subnet: "10.0.0.0/24"
amneziawg_default_port: "51820"
amneziawg_default_dns: "8.8.8.8,1.1.1.1"
amneziawg_wireguard_port: "51820"
