---
- name: System setup and packages
  ansible.builtin.import_tasks: packages.yml
  tags: [common, packages]

- name: Security and Firewall configuration
  ansible.builtin.import_tasks: security.yml
  tags: [common, security]

- name: Performance tuning (Sysctl, ZRAM, Network)
  ansible.builtin.import_tasks: tuning.yml
  tags: [common, tuning]
