---
- name: Ensure Syncthing directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0755"
  loop:
    - "{{ syncthing_compose_dir }}"
    - "{{ syncthing_data_dir }}"

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ syncthing_compose_dir }}/docker-compose.yml"
    mode: "0640"
    owner: "{{ deploy_user }}"
    group: docker

- name: Allow Syncthing ports (UFW)
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop:
    - { port: "22000", proto: "tcp", comment: "Syncthing Transfer TCP" }
    - { port: "22000", proto: "udp", comment: "Syncthing Transfer UDP" }
    - { port: "21027", proto: "udp", comment: "Syncthing Discovery" }

- name: Deploy Syncthing Stack
  community.docker.docker_compose_v2:
    project_src: "{{ syncthing_compose_dir }}"
    state: present
    pull: always
    remove_orphans: true
  become: true
  become_user: "{{ deploy_user }}"
