---
- name: Validate required variables
  ansible.builtin.assert:
    that:
      - gatus.domain is defined
      - deploy_user is defined
    fail_msg: "Required variables missing for Gatus"
  tags: [gatus, check]

- name: Ensure Gatus directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0755"
  loop:
    - "{{ gatus.path }}"
    - "{{ gatus.path }}/config"
    - "{{ gatus.path }}/data"
  tags: [gatus, filesystem]

- name: Render config.yaml
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ gatus.path }}/config/config.yaml"
    mode: "0644"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: Restart Gatus
  tags: [gatus, config]

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ gatus.path }}/docker-compose.yml"
    mode: "0640"
    owner: "{{ deploy_user }}"
    group: docker
  tags: [gatus, config]

- name: Deploy Gatus Stack
  community.docker.docker_compose_v2:
    project_src: "{{ gatus.path }}"
    state: present
    # Pull 'missing' if version is pinned, 'always' if latest
    pull: "{{ 'always' if 'latest' in gatus.image else 'missing' }}"
    remove_orphans: true
  become: true
  become_user: "{{ deploy_user }}"
  tags: [gatus, deploy]
